language: ruby
cache: bundler
rvm:
  - 2.3.1
before_install:
  - "gem install bundler"
  - "bundle config build.nokogiri --use-system-libraries"
  - "bundle install"
  - "npm install -g standard@8.0.0"
script:
  - exe/build
  - test $(git diff | wc -l) -eq "0" # make sure the build was already commited
  - git diff | cat
  - bin/scss-lint _sass
  - standard js/*.js
