language: ruby
cache: bundler
rvm:
  - 2.3.0
before_install:
  - "gem install bundler"
  - "bundle config build.nokogiri --use-system-libraries"
  - "bundle install"
  - "npm install -g standard@7.1.2"
script:
  - bin/jekyll build
  - bin/scss-lint _sass
  - standard js/*.js
