name: Max Jacobson
description: A dorkblog
url: http://maxjacobson.github.io
permalink: /:year/:title
markdown: kramdown
relative_permalinks: true
exclude: ["Gemfile", "Gemfile.lock", "Guardfile", "README.md"]