name: Max Jacobson
description: A dorkblog
url: http://maxjacobson.github.io
webmaster: max@maxjacobson.net
permalink: /:year/:title
markdown: kramdown
relative_permalinks: true
exclude: ["df.xml", "ex-feed.xml", "Gemfile", "Gemfile.lock", "Guardfile", "README.md"]