title: hardscrabble
author: Max Jacobson
description: the personal website of Max Jacobson, a programmer in New York
analytics_id: 'UA-4982721-15'

url: "http://hardscrabble.net"
baseurl: "/"
port: 1234

permalink: "/:year/:title"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "vendor"
  - "bin"
  - ".travis.yml"

markdown: kramdown
highlighter: pygments

gems:
  - jemoji
  - octopress-debugger

poole:
  word_separator: "-"

