title: hardscrabble
author: Max Jacobson
description: the personal website of Max Jacobson, a programmer in New York

url: 'http://hardscrabble.net'
baseurl: /
port: 1234

permalink: /:year/:title

exclude:
- "Gemfile"
- "Gemfile.lock"
- "README.md"
- "vendor"
- "bin"
- ".travis.yml"

markdown: kramdown
highlighter: pygments

gems:
  - jemoji
