title: "Hardscrabble"
author: "Maxwell Jacobson"
email: "max@hardscrabble.net"
description: "the personal website of Maxwell Jacobson, a programmer in New York"

url: "https://www.hardscrabble.net"
port: 1234

permalink: "/:year/:title/"

timezone: "America/New_York"

metaphorloop_metadata:
  title: "metaphor loop"
  subtitle: "a podcast about how we think about programming"
  description: "Listen to Maxwell Jacobson talk to programmers about how they think about programming."
  url: "https://www.hardscrabble.net/metaphorloop"
  cover_art: "https://s3.amazonaws.com/metaphorloop/metaphorloop.png"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "metaphorloop_episodes"
    values:
      layout: "metaphorloop_episode"

exclude:
  - "CNAME"
  - "README.md"
  - "bin"
  - "exe"
  - ".github"
  - ".ruby-version"
  - "prettier.config.js"
  - "package.json"
  - "pnpm-lock.yaml"
  - "node_modules"
  - ".node-version"

markdown: kramdown

kramdown:
    input: GFM
    hard_wrap: false

paginate: 10
paginate_path: "/page/:num/"

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives

collections:
  metaphorloop_episodes:
    output: true
    permalink: "/metaphorloop/:name/"

jekyll-archives:
  layouts:
    year: year-archive
    category: category-archive

  enabled:
    - year
    - categories
