#!/usr/bin/env ruby

ALLOW_LIST = [
  "_posts/2013-01-21-click-to-ugh.md"
]

Dir.glob("{_posts,_drafts}/**/*").each do |file|
  text = File.read(file)

  next if ALLOW_LIST.include?(file)

  if text.include?("youtube.com/embed")
    warn <<~MSG

      Includes non-responsive youtube embed: #{file}

      Reminder: you can make a youtube video responsive like this:

      {% include youtube.html id="G7KNmW9a75Y" %}
    MSG

    exit 1
  end

  if text.include?("player.vimeo")
    warn <<~MSG

      Includes non-responsive vimeo embed: #{file}

      Reminder: you can make a vimeo video responsive like this:

      {% include vimeo.html id="130172467" %}
    MSG

    exit 1
  end
end
