#!/usr/bin/env ruby

require "date"
require "irb"
require "yaml"

CUTOFF = Date.new(2023, 9, 3) # date I started including preview images
MAX_SIZE = 1 * 1024 * 1024 # 1 megabyte

Dir.glob("_posts/**/*").each do |file|
  match = file.match(%r{_posts/(\d{4}-\d{2}-\d{2})})
  raise if match.nil?
  date = Date.parse(match[1])

  next if date < CUTOFF

  frontmatter = YAML.load_file(file)
  preview_image = frontmatter.fetch("preview_image", nil)

  if preview_image.nil?
    warn <<~MSG
      [Preview image] #{file} is missing a preview image
    MSG

    exit 1
  end

  if !File.exist?(preview_image)
    warn <<~MSG
      [Preview image] #{file} references preview image #{preview_image} but that file does not exist
    MSG

    exit 1
  end

  if File.open(preview_image).size > MAX_SIZE
    warn <<~MSG
      [Preview image] #{file}'s preview image, #{preview_image}, is too large of a file and won't reliably preview everywhere
    MSG

    exit 1
  end

  puts <<~MSG
    [Preview image] OK #{file}
  MSG
end
