#!/usr/bin/env bash

set -euo pipefail

PATH="node_modules/.bin:$PATH"
PATH="bin:$PATH"
PATH="exe:$PATH"

check-responsive-video-embeds
build
htmlproofer _site --disable-external --no-enforce-https
prettier . --check
rubocop
