#!/usr/bin/env bash

set -euo pipefail

exe/check-preview-images
exe/check-responsive-video-embeds
exe/build
bin/htmlproofer _site --disable-external --no-enforce-https
npx -y prettier@3.4.1 . --check
