#!/usr/bin/env bash

set -euo pipefail

function updateDate() {
  sed "s/date: [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/date: $(date '+%Y-%m-%d %H:%M')/"
}

function draftToPost() {
  sed "s/_drafts\//_posts\/$(date '+%Y-%m-%d')-/"
}

set +u
if [ -z "$1" ]; then
  echo "usage: $0 _drafts/great-post.md"
  exit 1
fi
set -u

filename="$1"

if [[ ! -e "$filename" ]]; then
  echo "$filename does not exist"
  exit 1
fi

post="$(cat $filename | updateDate)"

newFilename="$(
  echo $filename | draftToPost
)"

echo "$post" > $newFilename

rm $filename
echo "Moved $filename to $newFilename"
